// Generated by CoffeeScript 2.3.2
var f2, fighters, warbands;

warbands = {
  "Steelheart's Champions": {
    name: "Steelheart's Champions",
    set: "Shadespire",
    num_fighters: 3
  },
  "Garricks's Reavers": {
    name: "Garricks's Reavers",
    set: "Shadespire",
    num_fighters: 5
  }
};

fighters = {
  "Severin Steelheart": {
    name: "Severin Steelheart",
    wounds: 4
  },
  "Angharad Brightshield": {
    name: "Angharad Brightshield",
    wounds: 4
  },
  "Obryn the Bold": {
    name: "Obryn the Bold",
    wounds: 4
  },
  "Garrick Gorebeard": {
    name: "Garrick Gorebeard",
    wounds: 4
  },
  "Blooded Saek": {
    name: "Blooded Saek",
    wounds: 3
  }
};

f2 = {
  cards: [
    {
      name: "Severin Steelheart",
      warband : "Steelheart's Champions",
      wounds: 3
    },
    {
      name: "Angharad Brightshield",
      warband : "Steelheart's Champions",
      wounds: 4
    },
    {
      name: "Garrick Gorebeard",
      warband : "Garrick's Reavers",
      wounds: 4
    },
    {
      name: "Blooded Saek",
      warband : "Garrick's Reavers",
      wounds: 3
    }
  ]
};


mywarband = warbands["Steelheart's Champions"]
myfighters = f2.cards.filter(fighter => fighter.warband == mywarband.name)

console.log(myfighters)

// console.log(f2.cards.filter(fighter => fighter.wounds > 3))
// console.log(f2.cards.filter(fighter => fighter.warband == "Garrick's Reavers"))